#!/usr/bin/expect
set timeout 1000
set host [lindex $argv 0]
set password [lindex $argv 1]

spawn ssh $host
 expect {
 "(yes/no)?"
  {
    send "yes\n"
    expect "*assword:" { send "$password\n"}
  }
 "*assword:"
  {
    send "$password\n"
  }
}
expect "100%"
expect eof